{
 "title": "ASG dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ASG Network In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": {
      "AutoScalingGroupName": "terraform-20250326095106702800000003"
     },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ASG Network Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": {
      "AutoScalingGroupName": "terraform-20250326095106702800000003"
     },
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ASG CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": {
      "AutoScalingGroupName": "terraform-20250326095106702800000003"
     },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}