{
 "title": "Lambda Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Lambda Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Lambda Concurrent Execution Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "metricName": "ConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Lambda Duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Incoming Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "metricName": "IncomingBytes",
     "namespace": "AWS/Logs",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/Logs", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "IncomingBytes", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "/aws/lambda/IntruderAlertLambda"
         },
         "property": { "name": "LogGroupName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(IncomingBytes) FROM \"AWS/Logs\" WHERE LogGroupName = '/aws/lambda/IntruderAlertLambda'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Incoming Log Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metricName": "IncomingLogEvents",
     "namespace": "AWS/Logs",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/Logs", "type": "functionParameter" },
        { "name": "LogGroupName", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "IncomingBytes", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(IncomingBytes) FROM SCHEMA(\"AWS/Logs\", LogGroupName)",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Delivery Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metricName": "DeliveryErrors",
     "namespace": "AWS/Logs",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/Logs", "type": "functionParameter" },
        { "name": "LogGroupName", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "IncomingBytes", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(IncomingBytes) FROM SCHEMA(\"AWS/Logs\", LogGroupName)",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Delivery Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metricName": "DeliveryThrottling",
     "namespace": "AWS/Logs",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/Logs", "type": "functionParameter" },
        { "name": "LogGroupName", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "IncomingBytes", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT AVG(IncomingBytes) FROM SCHEMA(\"AWS/Logs\", LogGroupName)",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda Error Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\n filter @message like \"[ERROR]\" |\n sort @timestamp desc |\n limit 20",
     "logGroups": [
      {
       "accountId": "746441023300",
       "arn": "arn:aws:logs:us-east-1:746441023300:log-group:/aws/lambda/IntruderAlertLambda:*",
       "name": "/aws/lambda/IntruderAlertLambda"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda Incoming Success Reply (Topic: sdk/test/python)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like /\"status\":\"Success\"/\n| filter @message like /\"topicName\":\"sdk\\/test\\/python\"/\n| stats count(*) as count by @timestamp, topicName\n",
     "logGroups": [
      {
       "accountId": "746441023300",
       "arn": "arn:aws:logs:us-east-1:746441023300:log-group:AWSIotLogsV2:*",
       "name": "AWSIotLogsV2"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "@timestamp",
      "topicName"
     ]
    }
   ]
  },
  {
   "title": "Lambda Incoming Success Reply (Topic: sdk/test/python)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like /\"status\":\"Success\"/\n| filter @message like /\"topicName\":\"sdk\\/test\\/python\"/\n| sort @timestamp desc\n| limit 20\n\n",
     "logGroups": [
      {
       "accountId": "746441023300",
       "arn": "arn:aws:logs:us-east-1:746441023300:log-group:AWSIotLogsV2:*",
       "name": "AWSIotLogsV2"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda Incoming Error Reply (Topic: sdk/test/python)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like /\"logLevel\":\"ERROR\"/\n| filter @message like /\"topicName\":\"sdk\\/test\\/python\"/\n| stats count(*) as count by @timestamp, topicName\n",
     "logGroups": [
      {
       "accountId": "746441023300",
       "arn": "arn:aws:logs:us-east-1:746441023300:log-group:AWSIotLogsV2:*",
       "name": "AWSIotLogsV2"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "@timestamp",
      "topicName"
     ]
    }
   ]
  },
  {
   "title": "Lambda Incoming Error Reply (Topic: sdk/test/python)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like /\"logLevel\":\"ERROR\"/\n| filter @message like /\"topicName\":\"sdk\\/test\\/python\"/\n| sort @timestamp desc\n| limit 20\n",
     "logGroups": [
      {
       "accountId": "746441023300",
       "arn": "arn:aws:logs:us-east-1:746441023300:log-group:AWSIotLogsV2:*",
       "name": "AWSIotLogsV2"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda Outgoing Success Reply (Topic: sdk/test/python1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like /\"status\":\"Success\"/\n| filter @message like /\"topicName\":\"sdk\\/test\\/python1\"/\n| stats count(*) as count by @timestamp, topicName\n",
     "logGroups": [
      {
       "accountId": "746441023300",
       "arn": "arn:aws:logs:us-east-1:746441023300:log-group:AWSIotLogsV2:*",
       "name": "AWSIotLogsV2"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "@timestamp",
      "topicName"
     ]
    }
   ]
  },
  {
   "title": "Lambda Outgoing Success Reply (Topic: sdk/test/python1)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like /\"status\":\"Success\"/\n| filter @message like /\"topicName\":\"sdk\\/test\\/python1\"/\n| sort @timestamp desc\n| limit 20\n",
     "logGroups": [
      {
       "accountId": "746441023300",
       "arn": "arn:aws:logs:us-east-1:746441023300:log-group:AWSIotLogsV2:*",
       "name": "AWSIotLogsV2"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda Outgoing Error Reply (Topic: sdk/test/python1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like /\"logLevel\":\"ERROR\"/\n| filter @message like /\"topicName\":\"sdk\\/test\\/python1\"/\n| stats count(*) as count by @timestamp, topicName\n",
     "logGroups": [
      {
       "accountId": "746441023300",
       "arn": "arn:aws:logs:us-east-1:746441023300:log-group:AWSIotLogsV2:*",
       "name": "AWSIotLogsV2"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "@timestamp",
      "topicName"
     ]
    }
   ]
  },
  {
   "title": "Lambda Outgoing Error Reply (Topic: sdk/test/python1)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like /\"logLevel\":\"ERROR\"/\n| filter @message like /\"topicName\":\"sdk\\/test\\/python1\"/\n| sort @timestamp desc\n| limit 20\n",
     "logGroups": [
      {
       "accountId": "746441023300",
       "arn": "arn:aws:logs:us-east-1:746441023300:log-group:AWSIotLogsV2:*",
       "name": "AWSIotLogsV2"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}